{
 "title": "Rust Exporter Example",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "query_result(facepunch_rust_players >= 0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server State",
   "type": "stat",
   "description": "Will report if the server is restarting",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "facepunch_rust_server_restarting{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "facepunch_rust_players{instance=\"$server\"}"
    },
    {
     "expr": "facepunch_rust_players_queued{instance=\"$server\"}"
    },
    {
     "expr": "facepunch_rust_players_joining{instance=\"$server\"}"
    },
    {
     "expr": "facepunch_rust_server_max_players{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "facepunch_rust_server_memory{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "facepunch_rust_server_network_in{instance=\"$server\"}"
    },
    {
     "expr": "facepunch_rust_server_network_out{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Framerate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "facepunch_rust_server_framerate{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "facepunch_rust_server_collections{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "facepunch_rust_server_entity_count{instance=\"$server\"}"
    }
   ]
  }
 ]
}